---
- name: 'Add Account Manager to BOINC client.' 
  hosts: boinc-windows

  vars_files:
    - vars/vars.yml
    - vars/winrm.yml
    - vars/boinccreds.yml
    - vars/domaincreds.yml

  tasks:

    - name: 'Ensure Ansible directory exists.'
      win_file: path={{ ansibledir }} state=directory

    - name: 'Start boincmgr.exe to start all BOINC processes.'
      raw: '{{ ansibledir }}\PsExec.exe -i -d -u "{{ domainuser }}" -p "{{ domainpassword }}" \\{{ item }} {{ boincmgr }}'
      with_items:
       - "{{ hostname }}"
      ignore_errors: yes
    
    - name: 'Push batch file to add Account Manager to BOINC.'
      win_template: src=templates/joinacctmgr.j2 dest='{{ ansibledir }}\joinacctmgr.bat'

    - name: 'Kill boincmgr.exe'
      raw: 'taskkill /F /IM boincmgr.exe'
      ignore_errors: yes

    - name: 'Execute batch file.'
      raw: '{{ ansibledir }}\joinacctmgr.bat'

    - name: 'Delete batch file.'
      win_file: path='{{ ansibledir }}\joinacctmgr.bat' state=absent

    - name: 'Start boincmgr.exe.'
      raw: '{{ ansibledir }}\PsExec.exe -i -d -u "{{ domainuser }}" -p "{{ domainpassword }}" \\{{ item }} {{ boincmgr }}'
      with_items:
       - "{{ hostname }}"
      ignore_errors: yes
