---
- name: 'Add BAM account manager to BOINC client.' 
  hosts: boinc-windows

  vars_files:
    - vars/vars.yml
    - vars/winrm.yml
    - vars/boinccreds.yml

  tasks:

    - name: 'Ensure Ansible directory exists.'
      win_file: path={{ ansibledir }} state=directory

    - name: 'Start boincmgr.exe to start all BOINC processes.'
      raw: '{{ ansibledir }}\PsExec.exe -i -d -u {{ domainuser }} -p {{ domainpassword }} \\{{ item }}\  "{{ boincmgr }}"'
      with_items:
       - "{{ hostname }}"
      ignore_errors: yes
    
    - name: 'Kill boincmgr.exe'
      raw: 'taskkill /F /IM boincmgr.exe'
      ignore_errors: yes

    - name: 'Add Account Manager to BOINC.'
      raw: '{{ boinccmdwin }} --join_acct_mgr {{ acctmgr }} {{ boincuser }} {{ boincpassword }}'

    - name: 'Start boincmgr.exe.'
      raw: '{{ ansibledir }}\PsExec.exe -i -d -u {{ domainuser }} -p {{ domainpassword }} \\{{ item }}\  "{{ boincmgr }}"'
      with_items:
       - "{{ hostname }}"
      ignore_errors: yes

