---
- name: 'Add Account Manager to BOINC client.' 
  hosts: boinc-windows

  vars_files:
    - vars/vars.yml
    - vars/winrm.yml

  tasks:

    - name: 'Ensure Ansible directory exists.'
      win_file: path={{ ansibledir }} state=directory

    - name: 'Copy BOINC install MSI'
      win_copy: src='{{ installmsi }}' dest='{{ ansibledir }}\{{ installmsi }}'

    - name: 'Install BOINC MSI'
      win_msi: path='{{ ansibiledir }}\{{ installmsi }}'
